name: Compile Arduino Sketches

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - uses: arduino/compile-sketches@v1.1.2
        with:
          fqbn: "SiliconLabs:silabs:thingplusmatter"
        
          sketch-paths: |
            - ./src/
